.TH cream-test-notified-submit "1" cream-test-notified-submit "GLITE Testsuite"

.SH NAME:
cream-test-notified-submit \- submit a sequence of jobs and wait for notifications

.SH SYNOPSIS
.B cream-test-notified-submit
[OPTION] -R | --resourceURI RESOURCEURI

.SH DESCRIPTION
Submit a given number jobs keeping track of their status via CEMonitor notifications. The test keeps a given number of job running on the CE.

.SH OPTIONS
.HP
\fB-p\fR, \fB--consumerPort\fR
NUMBER

.IP
define the port for the consumer service (DEFAULT is 9000)
.PP
.HP
\fB-D\fR, \fB--delegationType\fR
STRING

.IP
specify the delegation management type: single, one delegated proxy for all submissions, or multiple, one delegated proxy per job (DEFAULT is single)
.PP
.HP
\fB-h\fR, \fB--help\fR


.IP
Print the man pages for this command
.PP
.HP
\fB--interactive\fR


.IP
Enable the test control via terminal (EXPERIMENTAL)
.PP
.HP
\fB-j\fR, \fB--jdl\fR
STRING

.IP
define the path for the jdl file, if omitted 
a predefined jdl will be used with simple sleep as executable (5 times the rate)
.PP
.HP
\fB-l\fR, \fB--logConf\fR
STRING

.IP
Set the location of the configuration file for log4py, (DEFAULT as provided by log4py)
.PP
.HP
\fB-C\fR, \fB--maxConcurrentSubmit\fR
NUMBER

.IP
define the number of concurrent submit, (DEFAULT is 1)
.PP
.HP
\fB-m\fR, \fB--maxRunningJobs\fR
NUMBER

.IP
set the max number of job which can be enqueued in the service (DEFAULT 100)
.PP
.HP
\fB--nopurge\fR


.IP
Disable the purge operation for all jobs submitted (CRITICAL)
.PP
.HP
\fB-n\fR, \fB--numberOfJob\fR
NUMBER

.IP
set the number of jobs to submit (DEFAULT 1)
.PP
.HP
\fB-r\fR, \fB--rate\fR
NUMBER

.IP
set the notification rate in seconds for the subscription on CEMonitor (DEFAULT is 30s)
.PP
.HP
\fB-R\fR, \fB--resourceURI\fR
STRING

.IP
define the URI of the resource under testing, the format is <host>[:<port>]/cream-<lrms>-<queue>. This option is mandatory and no default value is defined
.PP
.HP
\fB--sotimeout\fR
NUMBER

.IP
Socket timeout in seconds (DEFAULT 30s)
.PP
.HP
\fB--valid\fR
STRING

.IP
set the voms-proxy duration in the format HH:MM (DEFAULT 00:10)
.PP
.HP
\fB--vo\fR
STRING

.IP
set the VO name to be used for the test; this parameter is mandatory whenever X509_USER_CERT and X509_USER_KEY are defined, no default is available
.PP
.SH ENVIRONMENT
.TP
.B GLITE_LOCATION
location of gLite packages (DEFAULT=/opt/glite)
.
.TP
.B X509_USER_PROXY
location of the user proxy
.
.TP
.B X509_USER_CERT
location of the user certificate, this variable has priority upon the X509_USER_PROXY variable
.
.TP
.B X509_USER_KEY
location of the user private key. The key must be protected by a passphrase.
.
.TP
.B X509_CONSUMER_CERT
location of the consumer certificate, if this variable is set together with X509_CONSUMER_KEY the test suite enables the notifications over secure channel
.
.TP
.B X509_CONSUMER_KEY
location of the consumer private key, if this variable is set together with X509_CONSUMER_CERT the test suite enables the notifications over secure channel. The key must be protected by a passphrase.
.
.TP
.B NOTIFIED_SUBMIT_CONFIG_FILE
location of the configuration file for this test. The configuration file contains a list of properties (the format is key=value); the set of keys correspond to the set of the long options of this test
.
